const express = require('express');
const app = express();
const PORT = 3000;
const path = require('path');


// need to write code to access controller page

console.log(__dirname);

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, './client/index.html'));
});

app.use('/dist', express.static(path.join(__dirname, './dist')))

app.post('/user',  /* middleware goes here */(req, res) =>
  res.status(200)
  /*   - Post / create user — middleware
    - Posts a new user, based on a schema model,  */
);

app.post('/save',  /* middlewaregoeshere */(req, res) =>
  res.status(200)
  /*  - Post / save button — middleware
- Allow user to save whatever is in saved pins object to the database
- This data is then returned upon login and displayed in the divs list (which will be generated by react elements so they can update live) and populated onto the map */
);

app.listen(PORT, () => console.log(`Server listening on port: ${PORT}`));
