const express = require('express');
const controller = require('../controllers/api');
const router = express.Router();

router.get('/', /* middlewaregoeshere */ (req, res) =>
    res.send('eat it');
    res.status(200)
);

router.get('/main', /* middleware goes here */ (req, res) => 
    res.status(200)
/*     - Get / login — middleware to call DB and capture data
    - Reads database for user info
    - Returns data with saved pins object */
 );

router.post('/user',  /* middleware goes here */ (req, res) => 
    res.status(200)
  /*   - Post / create user — middleware
    - Posts a new user, based on a schema model,  */
 );

router.post('/save',  /* middlewaregoeshere */ (req, res) =>
    res.status(200)
    /*  - Post / save button — middleware
 - Allow user to save whatever is in saved pins object to the database
 - This data is then returned upon login and displayed in the divs list (which will be generated by react elements so they can update live) and populated onto the map */
 );

module.exports = router;
